export const GOOGLE_LANG_MAP = {
  'af': 'Afrikaans',
  'ak': 'Twi',
  'am': 'Amharic',
  'ar': 'Arabic',
  'as': 'Assamese',
  'ay': 'Aymara',
  'az': 'Azerbaijani',
  'be': 'Belarusian',
  'bg': 'Bulgarian',
  'bho': 'Bhojpuri',
  'bm': 'Bambara',
  'bn': 'Bengali',
  'bs': 'Bosnian',
  'ca': 'Catalan',
  'ceb': 'Cebuano',
  'ckb': 'Kurdish (Sorani)',
  'co': 'Corsican',
  'cs': 'Czech',
  'cy': 'Welsh',
  'da': 'Danish',
  'de': 'German',
  'doi': 'Dogri',
  'dv': 'Dhivehi',
  'ee': 'Ewe',
  'el': 'Greek',
  'en': 'English',
  'eo': 'Esperanto',
  'es': 'Spanish',
  'et': 'Estonian',
  'eu': 'Basque',
  'fa': 'Persian',
  'fi': 'Finnish',
  'fr': 'French',
  'fy': 'Frisian',
  'ga': 'Irish',
  'gd': 'Scots Gaelic',
  'gl': 'Galician',
  'gn': 'Guarani',
  'gom': 'Konkani',
  'gu': 'Gujarati',
  'ha': 'Hausa',
  'haw': 'Hawaiian',
  'hi': 'Hindi',
  'hmn': 'Hmong',
  'hr': 'Croatian',
  'ht': 'Haitian Creole',
  'hu': 'Hungarian',
  'hy': 'Armenian',
  'id': 'Indonesian',
  'ig': 'Igbo',
  'ilo': 'Ilocano',
  'is': 'Icelandic',
  'it': 'Italian',
  'iw': 'Hebrew',
  'ja': 'Japanese',
  'jw': 'Javanese',
  'ka': 'Georgian',
  'kk': 'Kazakh',
  'km': 'Khmer',
  'kn': 'Kannada',
  'ko': 'Korean',
  'kri': 'Krio',
  'ku': 'Kurdish (Kurmanji)',
  'ky': 'Kyrgyz',
  'la': 'Latin',
  'lb': 'Luxembourgish',
  'lg': 'Luganda',
  'ln': 'Lingala',
  'lo': 'Lao',
  'lt': 'Lithuanian',
  'lus': 'Mizo',
  'lv': 'Latvian',
  'mai': 'Maithili',
  'mg': 'Malagasy',
  'mi': 'Maori',
  'mk': 'Macedonian',
  'ml': 'Malayalam',
  'mn': 'Mongolian',
  'mni-Mtei': 'Meiteilon (Manipuri)',
  'mr': 'Marathi',
  'ms': 'Malay',
  'mt': 'Maltese',
  'my': 'Myanmar (Burmese)',
  'ne': 'Nepali',
  'nl': 'Dutch',
  'no': 'Norwegian',
  'nso': 'Sepedi',
  'ny': 'Chichewa',
  'om': 'Oromo',
  'or': 'Odia (Oriya)',
  'pa': 'Punjabi',
  'pl': 'Polish',
  'ps': 'Pashto',
  'pt': 'Portuguese',
  'qu': 'Quechua',
  'ro': 'Romanian',
  'ru': 'Russian',
  'rw': 'Kinyarwanda',
  'sa': 'Sanskrit',
  'sd': 'Sindhi',
  'si': 'Sinhala',
  'sk': 'Slovak',
  'sl': 'Slovenian',
  'sm': 'Samoan',
  'sn': 'Shona',
  'so': 'Somali',
  'sq': 'Albanian',
  'sr': 'Serbian',
  'st': 'Sesotho',
  'su': 'Sundanese',
  'sv': 'Swedish',
  'sw': 'Swahili',
  'ta': 'Tamil',
  'te': 'Telugu',
  'tg': 'Tajik',
  'th': 'Thai',
  'ti': 'Tigrinya',
  'tk': 'Turkmen',
  'tl': 'Filipino',
  'tr': 'Turkish',
  'ts': 'Tsonga',
  'tt': 'Tatar',
  'ug': 'Uyghur',
  'uk': 'Ukrainian',
  'ur': 'Urdu',
  'uz': 'Uzbek',
  'vi': 'Vietnamese',
  'xh': 'Xhosa',
  'yi': 'Yiddish',
  'yo': 'Yoruba',
  'zh-CN': 'Chinese (Simplified)',
  'zh-TW': 'Chinese (Traditional)',
  'zu': 'Zulu'
};

export const GOOGLE_DOMAIN = [
  "translate.google.ac",
  "translate.google.ad",
  "translate.google.ae",
  "translate.google.al",
  "translate.google.am",
  "translate.google.as",
  "translate.google.at",
  "translate.google.az",
  "translate.google.ba",
  "translate.google.be",
  "translate.google.bf",
  "translate.google.bg",
  "translate.google.bi",
  "translate.google.bj",
  "translate.google.bs",
  "translate.google.bt",
  "translate.google.by",
  "translate.google.ca",
  "translate.google.cat",
  "translate.google.cc",
  "translate.google.cd",
  "translate.google.cf",
  "translate.google.cg",
  "translate.google.ch",
  "translate.google.ci",
  "translate.google.cl",
  "translate.google.cm",
  "translate.google.cn",
  "translate.google.co.ao",
  "translate.google.co.bw",
  "translate.google.co.ck",
  "translate.google.co.cr",
  "translate.google.co.id",
  "translate.google.co.il",
  "translate.google.co.in",
  "translate.google.co.jp",
  "translate.google.co.ke",
  "translate.google.co.kr",
  "translate.google.co.ls",
  "translate.google.co.ma",
  "translate.google.co.mz",
  "translate.google.co.nz",
  "translate.google.co.th",
  "translate.google.co.tz",
  "translate.google.co.ug",
  "translate.google.co.uk",
  "translate.google.co.uz",
  "translate.google.co.ve",
  "translate.google.co.vi",
  "translate.google.co.za",
  "translate.google.co.zm",
  "translate.google.co.zw",
  "translate.google.co",
  "translate.google.com.af",
  "translate.google.com.ag",
  "translate.google.com.ai",
  "translate.google.com.ar",
  "translate.google.com.au",
  "translate.google.com.bd",
  "translate.google.com.bh",
  "translate.google.com.bn",
  "translate.google.com.bo",
  "translate.google.com.br",
  "translate.google.com.bz",
  "translate.google.com.co",
  "translate.google.com.cu",
  "translate.google.com.cy",
  "translate.google.com.do",
  "translate.google.com.ec",
  "translate.google.com.eg",
  "translate.google.com.et",
  "translate.google.com.fj",
  "translate.google.com.gh",
  "translate.google.com.gi",
  "translate.google.com.gt",
  "translate.google.com.hk",
  "translate.google.com.jm",
  "translate.google.com.kh",
  "translate.google.com.kw",
  "translate.google.com.lb",
  "translate.google.com.lc",
  "translate.google.com.ly",
  "translate.google.com.mm",
  "translate.google.com.mt",
  "translate.google.com.mx",
  "translate.google.com.my",
  "translate.google.com.na",
  "translate.google.com.ng",
  "translate.google.com.ni",
  "translate.google.com.np",
  "translate.google.com.om",
  "translate.google.com.pa",
  "translate.google.com.pe",
  "translate.google.com.pg",
  "translate.google.com.ph",
  "translate.google.com.pk",
  "translate.google.com.pr",
  "translate.google.com.py",
  "translate.google.com.qa",
  "translate.google.com.sa",
  "translate.google.com.sb",
  "translate.google.com.sg",
  "translate.google.com.sl",
  "translate.google.com.sv",
  "translate.google.com.tj",
  "translate.google.com.tr",
  "translate.google.com.tw",
  "translate.google.com.ua",
  "translate.google.com.uy",
  "translate.google.com.vc",
  "translate.google.com.vn",
  "translate.google.com",
  "translate.google.cv",
  "translate.google.cx",
  "translate.google.cz",
  "translate.google.de",
  "translate.google.dj",
  "translate.google.dk",
  "translate.google.dm",
  "translate.google.dz",
  "translate.google.ee",
  "translate.google.es",
  "translate.google.eu",
  "translate.google.fi",
  "translate.google.fm",
  "translate.google.fr",
  "translate.google.ga",
  "translate.google.ge",
  "translate.google.gf",
  "translate.google.gg",
  "translate.google.gl",
  "translate.google.gm",
  "translate.google.gp",
  "translate.google.gr",
  "translate.google.gy",
  "translate.google.hn",
  "translate.google.hr",
  "translate.google.ht",
  "translate.google.hu",
  "translate.google.ie",
  "translate.google.im",
  "translate.google.io",
  "translate.google.iq",
  "translate.google.is",
  "translate.google.it",
  "translate.google.je",
  "translate.google.jo",
  "translate.google.kg",
  "translate.google.ki",
  "translate.google.kz",
  "translate.google.la",
  "translate.google.li",
  "translate.google.lk",
  "translate.google.lt",
  "translate.google.lu",
  "translate.google.lv",
  "translate.google.md",
  "translate.google.me",
  "translate.google.mg",
  "translate.google.mk",
  "translate.google.ml",
  "translate.google.mn",
  "translate.google.ms",
  "translate.google.mu",
  "translate.google.mv",
  "translate.google.mw",
  "translate.google.ne",
  "translate.google.nf",
  "translate.google.nl",
  "translate.google.no",
  "translate.google.nr",
  "translate.google.nu",
  "translate.google.pl",
  "translate.google.pn",
  "translate.google.ps",
  "translate.google.pt",
  "translate.google.ro",
  "translate.google.rs",
  "translate.google.ru",
  "translate.google.rw",
  "translate.google.sc",
  "translate.google.se",
  "translate.google.sh",
  "translate.google.si",
  "translate.google.sk",
  "translate.google.sm",
  "translate.google.sn",
  "translate.google.so",
  "translate.google.sr",
  "translate.google.st",
  "translate.google.td",
  "translate.google.tg",
  "translate.google.tk",
  "translate.google.tl",
  "translate.google.tm",
  "translate.google.tn",
  "translate.google.to",
  "translate.google.tt",
  "translate.google.us",
  "translate.google.vg",
  "translate.google.vu",
  "translate.google.ws"
]

export type TGoogleType = 'api1' | 'api2' | 'api3' | 'api4' | 'rpc';
export type TGoogleDomain = Lowercase<typeof GOOGLE_DOMAIN[number]>;

export type TGoogleLangCode = keyof typeof GOOGLE_LANG_MAP;
export type TGoogleLangCodeExtend = 'auto' | keyof typeof GOOGLE_LANG_MAP | string;
export type TGoogleLangCodeName = typeof GOOGLE_LANG_MAP[TGoogleLangCode];
